### ISSUE TITLE
Segment orientation

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [raphaeldussin/brushcutter#3]
How do I know if the segment is on the left or right  edge of the domain? 

"imin,imax" as arguments for segment generation should be replaced with "istart,iend"

**Comment by MJHarrison-GFDL** [comment]
I am going to suggest "istart,iend". Is that OK?  Keeping "imin,imax" as well and adding an "orientation" attribute for ilist. 

How about a right-handed notation with orientation=0==W-E;1==S-N;2==E-W;3==N-S ?

**Comment by raphaeldussin** [comment]
done
